### PR TITLE
New Go server with moderation

### PR DESCRIPTION
**Pull request by jfontan**
This new version should work the same as the ruby server with these additions:

* Admin interface to moderate effects
* HTTPS server
* Uses sqlite instead of mongo (the current server is using an ancient version of mongodb)
* Comes with two github actions that run when a new release is created:
  * Creates binaries so development on templates and js can be done without a go compiler
  * Creates docker image ready to deploy in the server

It's deployed for testing at https://glsl.zooloo.org. More information in these two comments:

* https://github.com/mrdoob/glsl-sandbox/issues/36#issuecomment-881673966
* https://github.com/mrdoob/glsl-sandbox/issues/36#issuecomment-881920371

I still have to create a tool to add moderators but the server functionality should be mostly finished. I've tested it but there may be bugs.

If you are OK with these changes I can start preparing the migration.

### CODE REVIEW

**Comment by mrdoob** [comment]
Sounds great to me!

**Comment by jfontan** [comment]
The data was migrated to the new server. Everything seems to be working fine except for the previous and next page links that now appear to the right of the thumbnails.

**Comment by mrdoob** [comment]
@jfontan I think https://github.com/mrdoob/glsl-sandbox/commit/6d8314a37163a074e433cd94bffd090d6eae9c6c should fix it?

**Comment by mrdoob** [comment]
How do I push to production? Making a new release?

**Comment by jfontan** [comment]
> How do I push to production? Making a new release?

Right now with a new release it creates the docker container that will be deployed in the server. The deploy part is still not automated. I do it manually after the docker container is generated. I'm preparing the webhook to do automatic deployment after release. I'll send the instructions to setup the webhook in the repository by email.

**Pull request merged**
